### ISSUE TITLE
JS shopping cart module - third party authentification

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-javascript-shoppingcart#3]
@tatarincev commented on [Fri Dec 09 2016](https://github.com/VirtoCommerce/vc-platform/issues/681)

Main goal for js cart authentication looks like this:
We should get user id on js cart client script by reading special known cookie or other header which can be assigned in other applications

Resources:
https://github.com/openiddict/openiddict-core
https://auth0.com/
https://auth0.com/blog/cookies-vs-tokens-definitive-guide/

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
