### ISSUE TITLE
Create and submit WordPress plugin for javascript shopping cart

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-javascript-shoppingcart#4]
@Woland2k commented on [Fri Sep 30 2016](https://github.com/VirtoCommerce/vc-platform/issues/637)

Create a new plugin "Virto Commerce shopping cart plugin" for wordpress and submit it here: https://wordpress.org/plugins/add/. Plugin should add a buton on the post screen that allows to add product to any post page.

---

@Woland2k commented on [Mon Oct 17 2016](https://github.com/VirtoCommerce/vc-platform/issues/637#issuecomment-254262236)

This is not done.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
